SELECT DNOMBRE, DEP_NO
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO
		HAVING COUNT(EMP_NO) > 0);
		
SELECT *
FROM PEDIDOS
WHERE FECHA_PEDIDO = (SELECT FECHA_PEDIDO
		      FROM PEDIDOS
		      ORDER BY 1
		      LIMIT 1);
		      
SELECT OFICIO, SUM(SALARIO) AS "Suma salario"
FROM EMPLEADOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM DEPARTAMENTOS
		WHERE DNOMBRE = 'VENTAS')
GROUP BY OFICIO;