-- NOTA FINAL: 6.76

-- EJERCICIO 1: BIEN 

SELECT APELLIDO, SALARIO
FROM EMPLEADOS
WHERE SALARIO > (SELECT AVG(SALARIO)
		 FROM EMPLEADOS);

-- EJERCICIO 2: BIEN 
 
SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE APELLIDO = 'GARRIDO');
		
-- EJERCICIO 3: BIEN

SELECT *
FROM EMPLEADOS
WHERE (OFICIO, DEP_NO) = (SELECT OFICIO, DEP_NO
			  FROM EMPLEADOS
			  WHERE APELLIDO = 'ALONSO');
			  
-- EJERCICIO 4: Aquí puse 'ALONSO' en vez de 'GARRIDO', pero cumple la función de la subconsulta. BIEN

SELECT *
FROM EMPLEADOS
WHERE OFICIO = (SELECT OFICIO
		 FROM EMPLEADOS
		 WHERE APELLIDO = 'ALONSO');
		 
-- EJERCICIO 5: MAL

SELECT *
FROM EMPLEADOS
WHERE SALARIO > (SELECT SALARIO
		 FROM EMPLEADOS
		 WHERE DEP_NO = 30
		 LIMIT 1);
		 
-- EJERCICIO 6: BIEN

SELECT COUNT(*) AS Num_empleados
FROM EMPLEADOS
WHERE OFICIO = 'VENDEDOR'
AND DEP_NO = (SELECT DEP_NO
	      FROM DEPARTAMENTOS
	      WHERE DNOMBRE = 'VENTAS');

-- EJERCICIO 7: BIEN

SELECT OFICIO, SUM(SALARIO) AS Suma_salario
FROM EMPLEADOS	
WHERE DEP_NO = (SELECT DEP_NO
		FROM DEPARTAMENTOS
		WHERE DNOMBRE = 'VENTAS')
GROUP BY OFICIO;

-- EJERCICIO 8: BIEN

SELECT *
FROM EMPLEADOS
WHERE EMP_NO IN (SELECT EMP_NO
		 FROM EMPLEADOS
		 WHERE DEP_NO NOT IN (SELECT DEP_NO
					  FROM DEPARTAMENTOS
					  WHERE LOCALIDAD = 'MADRID'
					  OR LOCALIDAD = 'BARCELONA'));

-- EJERCICIO 9: BIEN

SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		 FROM EMPLEADOS
		 WHERE FECHA_ALTA < '1982-01-01');

-- EJERCICIO 10: BIEN

SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO
		HAVING COUNT(*) > 2);
		
-- EJERCICIO 11: BIEN

SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		 FROM EMPLEADOS
		 GROUP BY DEP_NO
		 HAVING COUNT(*) >= 1);
		 
-- EJERCICIO 12: MAL

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		 FROM EMPLEADOS
		 WHERE EMP_NO IN (SELECT EMP_NO
				 FROM EMPLEADOS
				 WHERE COMISION IS NULL));
				 
-- EJERCICIO 13: BIEN

SELECT *
FROM EMPLEADOS
WHERE SALARIO > (SELECT SALARIO
		 FROM EMPLEADOS
		 WHERE DEP_NO = 20
		 LIMIT 1);
		 
-- EJERCICIO 14: BIEN

SELECT *
FROM DEPARTAMENTOS
GROUP BY DEP_NO
HAVING DEP_NO NOT IN (SELECT DISTINCT DEP_NO
		      FROM EMPLEADOS);
		
-- EJERCICIO 15: MAL

SELECT *
FROM DEPARTAMENTOS
GROUP BY DEP_NO
HAVING DEP_NO IN (SELECT DISTINCT DEP_NO
		  FROM EMPLEADOS
		  GROUP BY DEP_NO
		  HAVING COUNT(*) > 1);
		  
-- EJERCICIO 16: BIEN

SELECT LOCALIDAD
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE IFNULL(COMISION, 0) > (SELECT SALARIO*0.1
				  FROM EMPLEADOS
				  LIMIT 1));
				  
-- EJERCICIO 17: BIEN

SELECT *
FROM EMPLEADOS
WHERE (OFICIO, FECHA_ALTA) = (SELECT OFICIO, FECHA_ALTA
			      FROM EMPLEADOS
			      WHERE APELLIDO = 'GARRIDO');

-- EJERCICIO 18: MAL

SELECT *
FROM EMPLEADOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE APELLIDO = 'JIMENEZ')
GROUP BY EMP_NO
HAVING MAX(SALARIO);

-- EJERCICIO 19: MAL

SELECT *
FROM EMPLEADOS e1
WHERE EMP_NO = (SELECT EMP_NO
		FROM EMPLEADOS
		WHERE e1.DEP_NO = DEP_NO
		LIMIT 1)
GROUP BY EMP_NO
HAVING MAX(SALARIO);

-- EJERCICIO 20: BIEN

SELECT DISTINCT *
FROM EMPLEADOS
WHERE (DIRECTOR, DEP_NO) = (SELECT DIRECTOR, DEP_NO
			    FROM EMPLEADOS
			    WHERE APELLIDO = 'ALONSO')

GROUP BY EMP_NO
HAVING APELLIDO <> 'ALONSO';

-- EJERCICIO 21: BIEN

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO 
		HAVING AVG(SALARIO) >= (SELECT AVG(SALARIO)
				       FROM EMPLEADOS));
				       
-- EJERCICIO 22: BIEN

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO 
		HAVING AVG(SALARIO) > (SELECT AVG(SALARIO)/2
				       FROM EMPLEADOS));
				       
-- EJERCICIO 23: MAL

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO
		HAVING SUM(SALARIO)
		OR MIN(SALARIO));
		
-- EJERCICIO 24: BIEN

SELECT DNOMBRE, DEP_NO
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE OFICIO = 'VENDEDOR');

-- EJERCICIO 25: BIEN

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE EMP_NO = (SELECT EMP_NO
				FROM EMPLEADOS
				WHERE OFICIO = (SELECT OFICIO
						FROM EMPLEADOS
						WHERE APELLIDO = 'GIL')
				ORDER BY FECHA_ALTA ASC));
				
-- EJERCICIO 26: MAL

SELECT *
FROM EMPLEADOS e1
WHERE SALARIO IN (SELECT MAX(SALARIO)
		  FROM EMPLEADOS
		  WHERE e1.OFICIO = OFICIO);

-- EJERCICIO 27: MAL

SELECT *
FROM EMPLEADOS e1
WHERE FECHA_ALTA IN (SELECT MIN(FECHA_ALTA)
		  FROM EMPLEADOS
		  WHERE e1.OFICIO = OFICIO);
		  
-- EJERCICIO 28: MAL

SELECT *
FROM EMPLEADOS e1
WHERE SALARIO IN (SELECT MIN(SALARIO)
		  FROM EMPLEADOS
		  WHERE e1.OFICIO = OFICIO);