USE CURSO;

-- EJERCICIO 1

SELECT CLIENTE_NO, NOMBRE
FROM CLIENTES
WHERE VENDEDOR_NO = (SELECT EMP_NO
		     FROM EMPLEADOS
		     WHERE APELLIDO = 'CALVO');

-- EJERCICIO 2

SELECT PEDIDO_NO, PRODUCTO_NO, FECHA_PEDIDO
FROM PEDIDOS
WHERE CLIENTE_NO = (SELECT CLIENTE_NO
		    FROM CLIENTES
		    WHERE NOMBRE = 'EDICIONES SANZ');
		    
-- EJERCICIO 3

SELECT CLIENTE_NO, NOMBRE, LIMITE_CREDITO
FROM CLIENTES
WHERE LIMITE_CREDITO > (SELECT LIMITE_CREDITO
			FROM CLIENTES
			GROUP BY LIMITE_CREDITO
			HAVING AVG(LIMITE_CREDITO)
			LIMIT 1);

-- EJERCICIO 4

SELECT *
FROM PRODUCTOS
WHERE PRECIO_ACTUAL = (SELECT PRECIO_ACTUAL
		       FROM PRODUCTOS
		       GROUP BY PRECIO_ACTUAL
		       HAVING MAX(PRECIO_ACTUAL)
		       LIMIT 1);
		       
-- EJERCICIO 5

SELECT NOMBRE, CLIENTE_NO
FROM CLIENTES
WHERE CLIENTE_NO IN (SELECT CLIENTE_NO
		    FROM PEDIDOS
		    WHERE PRODUCTO_NO = (SELECT PRODUCTO_NO
					 FROM PRODUCTOS
					 WHERE DESCRIPCION = 'DESTRUCTORA DE PAPEL A3'));

-- EJERCICIO 6

SELECT APELLIDO, OFICIO
FROM EMPLEADOS
WHERE EMP_NO IN (SELECT VENDEDOR_NO
		 FROM CLIENTES
		 GROUP BY VENDEDOR_NO
		 HAVING COUNT(*) > 2);
		     
SELECT *
FROM CLIENTES;
		     

-- EJERCICIO 7

SELECT APELLIDO, OFICIO
FROM EMPLEADOS
WHERE DEP_NO = 10
AND OFICIO IN (SELECT OFICIO
	       FROM EMPLEADOS
	       WHERE DEP_NO = (SELECT DEP_NO
				FROM DEPARTAMENTOS
				WHERE DNOMBRE = 'VENTAS'));

SELECT *
FROM EMPLEADOS;

-- EJERCICIO 8

SELECT *
FROM EMPLEADOS
WHERE EMP_NO IN (SELECT VENDEDOR_NO
		 FROM CLIENTES
		 WHERE CLIENTE_NO NOT IN (SELECT DISTINCT CLIENTE_NO
				     FROM PEDIDOS));

-- EJERCICIO 9

SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE EMP_NO IN (SELECT EMP_NO
				FROM EMPLEADOS
				GROUP BY EMP_NO
				HAVING MAX(SALARIO)));
				
-- EJERCICIO 10

SELECT APELLIDO, EMP_NO
FROM EMPLEADOS emp1
WHERE SALARIO < (SELECT AVG(SALARIO)
		 FROM EMPLEADOS
		 WHERE emp1.DEP_NO = DEP_NO);
		 
-- EJERCICIO 11

SELECT NOMBRE, LOCALIDAD
FROM CLIENTES
WHERE CLIENTE_NO IN (SELECT CLIENTE_NO
		     FROM PEDIDOS
		     WHERE CLIENTE_NO IN (SELECT DISTINCT CLIENTE_NO
					  FROM PEDIDOS));
					  
-- EJERCICIO 12

SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO 
		ORDER BY MIN(SALARIO+IFNULL(COMISION, 0)) ASC
		LIMIT 1);

