USE CURSO;

-- EJERCICIO 1

SELECT DNOMBRE, DEP_NO
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO
		HAVING COUNT(*) > 0
);

-- EJERCICIO 2

SELECT *
FROM PEDIDOS
WHERE FECHA_PEDIDO = (SELECT FECHA_PEDIDO
		      FROM PEDIDOS
		      GROUP BY FECHA_PEDIDO
		      HAVING FECHA_PEDIDO = MAX(FECHA_PEDIDO)
		      LIMIT 1)
ORDER BY FECHA_PEDIDO DESC;

-- EJERCICIO 3

SELECT OFICIO, SUM(SALARIO)
FROM EMPLEADOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM DEPARTAMENTOS
		WHERE DNOMBRE = 'VENTAS')
GROUP BY OFICIO;

-- EJERCICIO 4

SELECT *
FROM PRODUCTOS
WHERE PRODUCTO_NO = (SELECT PRODUCTO_NO
		     FROM PEDIDOS
		     GROUP BY PRODUCTO_NO
		     HAVING MAX(UNIDADES)
		     LIMIT 1)
LIMIT 1;
		     
-- EJERCICIO 5

SELECT *
FROM PEDIDOS
WHERE PRODUCTO_NO = (SELECT PRODUCTO_NO
		     FROM PEDIDOS
		     GROUP BY PRODUCTO_NO
		     HAVING MAX(UNIDADES)
		     LIMIT 1
);

-- EJERCICIO 6

SELECT EMP_NO, APELLIDO, COMISION
FROM EMPLEADOS
WHERE IFNULL(COMISION,0) = (SELECT IFNULL(COMISION,0)
		  FROM EMPLEADOS
		  GROUP BY COMISION
		  HAVING AVG(SALARIO)
		  LIMIT 1);
