-- EJERCICIO 1

SELECT APELLIDO, SALARIO
FROM EMPLEADOS
WHERE SALARIO > (SELECT AVG(SALARIO)
		 FROM EMPLEADOS);

-- EJERCICIO 2
 
SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE APELLIDO = 'GARRIDO');
		
-- EJERCICIO 3

SELECT *
FROM EMPLEADOS
WHERE (OFICIO, DEP_NO) = (SELECT OFICIO, DEP_NO
			  FROM EMPLEADOS
			  WHERE APELLIDO = 'ALONSO');
			  
-- EJERCICIO 4

SELECT *
FROM EMPLEADOS
WHERE OFICIO = (SELECT OFICIO
		 FROM EMPLEADOS
		 WHERE APELLIDO = 'ALONSO');
		 
-- EJERCICIO 5

SELECT *
FROM EMPLEADOS
WHERE SALARIO > (SELECT SALARIO
		 FROM EMPLEADOS
		 WHERE DEP_NO = 30
		 LIMIT 1);
		 
-- EJERCICIO 6

SELECT COUNT(*) AS Num_empleados
FROM EMPLEADOS
WHERE OFICIO = 'VENDEDOR'
AND DEP_NO = (SELECT DEP_NO
	      FROM DEPARTAMENTOS
	      WHERE DNOMBRE = 'VENTAS');

-- EJERCICIO 7

SELECT OFICIO, SUM(SALARIO) AS Suma_salario
FROM EMPLEADOS	
WHERE DEP_NO = (SELECT DEP_NO
		FROM DEPARTAMENTOS
		WHERE DNOMBRE = 'VENTAS')
GROUP BY OFICIO;

-- EJERCICIO 8

SELECT *
FROM EMPLEADOS
WHERE EMP_NO IN (SELECT EMP_NO
		 FROM EMPLEADOS
		 WHERE DEP_NO NOT IN (SELECT DEP_NO
					  FROM DEPARTAMENTOS
					  WHERE LOCALIDAD = 'MADRID'
					  OR LOCALIDAD = 'BARCELONA'));

-- EJERCICIO 9

SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		 FROM EMPLEADOS
		 WHERE FECHA_ALTA < '1982-01-01');

-- EJERCICIO 10

SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO
		HAVING COUNT(*) > 2);
		
-- EJERCICIO 11

SELECT DNOMBRE
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		 FROM EMPLEADOS
		 GROUP BY DEP_NO
		 HAVING COUNT(*) >= 1);
		 
-- EJERCICIO 12

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		 FROM EMPLEADOS
		 WHERE EMP_NO IN (SELECT EMP_NO
				 FROM EMPLEADOS
				 WHERE COMISION IS NULL));
				 
-- EJERCICIO 13

SELECT *
FROM EMPLEADOS
WHERE SALARIO > (SELECT SALARIO
		 FROM EMPLEADOS
		 WHERE DEP_NO = 20
		 LIMIT 1);
		 
-- EJERCICIO 14

SELECT *
FROM DEPARTAMENTOS
GROUP BY DEP_NO
HAVING DEP_NO NOT IN (SELECT DISTINCT DEP_NO
		      FROM EMPLEADOS);
		
-- EJERCICIO 15

SELECT *
FROM DEPARTAMENTOS
GROUP BY DEP_NO
HAVING DEP_NO IN (SELECT DISTINCT DEP_NO
		  FROM EMPLEADOS
		  GROUP BY DEP_NO
		  HAVING COUNT(*) > 1);
		  
-- EJERCICIO 16

SELECT LOCALIDAD
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE IFNULL(COMISION, 0) > (SELECT SALARIO*0.1
				  FROM EMPLEADOS
				  LIMIT 1));
				  
-- EJERCICIO 17

SELECT *
FROM EMPLEADOS
WHERE (OFICIO, FECHA_ALTA) = (SELECT OFICIO, FECHA_ALTA
			      FROM EMPLEADOS
			      WHERE APELLIDO = 'GARRIDO');

-- EJERCICIO 18

SELECT *
FROM EMPLEADOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE APELLIDO = 'JIMENEZ')
GROUP BY EMP_NO
HAVING MAX(SALARIO);

-- EJERCICIO 19

SELECT *
FROM EMPLEADOS e1
WHERE EMP_NO = (SELECT EMP_NO
		FROM EMPLEADOS
		WHERE e1.DEP_NO = DEP_NO
		LIMIT 1)
GROUP BY EMP_NO
HAVING MAX(SALARIO);

-- EJERCICIO 20

SELECT DISTINCT *
FROM EMPLEADOS
WHERE (DIRECTOR, DEP_NO) = (SELECT DIRECTOR, DEP_NO
			    FROM EMPLEADOS
			    WHERE APELLIDO = 'ALONSO')

GROUP BY EMP_NO
HAVING APELLIDO <> 'ALONSO';

-- EJERCICIO 21

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO 
		HAVING AVG(SALARIO) >= (SELECT AVG(SALARIO)
				       FROM EMPLEADOS));
				       
-- EJERCICIO 22

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO 
		HAVING AVG(SALARIO) > (SELECT AVG(SALARIO)/2
				       FROM EMPLEADOS));
				       
-- EJERCICIO 23

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		GROUP BY DEP_NO
		HAVING SUM(SALARIO)
		OR MIN(SALARIO));
		
-- EJERCICIO 24

SELECT DNOMBRE, DEP_NO
FROM DEPARTAMENTOS
WHERE DEP_NO IN (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE OFICIO = 'VENDEDOR');

-- EJERCICIO 25

SELECT *
FROM DEPARTAMENTOS
WHERE DEP_NO = (SELECT DEP_NO
		FROM EMPLEADOS
		WHERE EMP_NO = (SELECT EMP_NO
				FROM EMPLEADOS
				WHERE OFICIO = (SELECT OFICIO
						FROM EMPLEADOS
						WHERE APELLIDO = 'GIL')
				ORDER BY FECHA_ALTA ASC));
				
-- EJERCICIO 26

SELECT *
FROM EMPLEADOS e1
WHERE SALARIO IN (SELECT MAX(SALARIO)
		  FROM EMPLEADOS
		  WHERE e1.OFICIO = OFICIO);

-- EJERCICIO 27

SELECT *
FROM EMPLEADOS e1
WHERE FECHA_ALTA IN (SELECT MIN(FECHA_ALTA)
		  FROM EMPLEADOS
		  WHERE e1.OFICIO = OFICIO);
		  
-- EJERCICIO 28

SELECT *
FROM EMPLEADOS e1
WHERE SALARIO IN (SELECT MIN(SALARIO)
		  FROM EMPLEADOS
		  WHERE e1.OFICIO = OFICIO);