SELECT EMP_NO, DATE_FORMAT(FECHA_ALTA, '%e de %M de %Y')
FROM EMPLEADOS;

SELECT LEFT(APELLIDO, LENGTH(APELLIDO)-3) "Apellido"
FROM EMPLEADOS
WHERE LENGTH(APELLIDO) > 6
ORDER BY APELLIDO ASC;

SELECT SALARIO "Salario", (SALARIO*3)/100 "Importe salario",
SALARIO+(SALARIO*3)/100 "Salario total"
FROM EMPLEADOS
WHERE COMISION IS NULL
ORDER BY APELLIDO ASC;

SELECT *
FROM EMPLEADOS
WHERE (SALARIO + IFNULL(COMISION, 0)) > 2000
AND (SALARIO > 1800 OR IFNULL(COMISION,0) > 500);

SELECT *
FROM EMPLEADOS
WHERE OFICIO='DIRECTOR'
ORDER BY FECHA_ALTA ASC
LIMIT 1;

SELECT *
FROM EMPLEADOS
WHERE DEP_NO IN (20, 30)
ORDER BY SALARIO DESC
LIMIT 2;