USE CURSO;

SELECT *
FROM EMPLEADOS
WHERE FECHA_ALTA >= '1981-5-1';

SELECT APELLIDO, DATEDIFF('2004-12-31', FECHA_ALTA) "DIAS_TRABAJO"
FROM EMPLEADOS;

SELECT APELLIDO, FECHA_ALTA, DAYNAME(FECHA_ALTA) AS DIA_SEMANA
FROM EMPLEADOS;

SELECT (SALARIO+IFNULL(COMISION, 0)) AS IMPORTE_TOTAL
FROM EMPLEADOS
WHERE OFICIO = 'VENDEDOR';

SELECT EMP_NO, APELLIDO, OFICIO
FROM EMPLEADOS
WHERE APELLIDO LIKE '%O' AND OFICIO LIKE 'V%';

SELECT RPAD(DNOMBRE, 36, '*') AS DNOMBRE
FROM DEPARTAMENTOS;

SELECT REPLACE(APELLIDO, 'A', '*') AS APELLIDOS_CAMBIADOS
FROM EMPLEADOS;

SELECT SUBSTR(DNOMBRE, ((LENGTH(DNOMBRE)/2)+1), ((LENGTH(DNOMBRE)/2)+1)) AS DNOMBRE_MITAD
FROM DEPARTAMENTOS;

SELECT DEP_NO, OFICIO, APELLIDO, EMP_NO, DIRECTOR, FECHA_ALTA, SALARIO, COMISION
FROM EMPLEADOS;

SELECT DEP_NO, APELLIDO, (SALARIO+IFNULL(COMISION, 0)) AS SALARIO_TOTAL
FROM EMPLEADOS
ORDER BY DEP_NO AND SALARIO_TOTAL ASC;

SELECT APELLIDO, (SALARIO+IFNULL(COMISION, 0)) AS SALARIO_TOTAL
FROM EMPLEADOS
WHERE DEP_NO = 30
ORDER BY SALARIO_TOTAL AND APELLIDO ASC;

SELECT APELLIDO 
FROM EMPLEADOS
WHERE COMISION IS NULL
ORDER BY LENGTH(APELLIDO) ASC;

SELECT DNOMBRE, LENGTH(DNOMBRE) AS LONGITUD_NOMBRE
FROM DEPARTAMENTOS
ORDER BY LENGTH(DNOMBRE) DESC
LIMIT 1;

SELECT APELLIDO, FECHA_ALTA, DEP_NO
FROM EMPLEADOS
ORDER BY FECHA_ALTA ASC
LIMIT 4;