USE CURSO;

SELECT DEP_NO, COUNT(*) AS NUM_DIRECTORES, AVG(SALARIO) AS SALARIO_MEDIO
FROM EMPLEADOS
WHERE OFICIO = 'DIRECTOR'
GROUP BY DEP_NO
ORDER BY NUM_DIRECTORES;

SELECT DEP_NO, AVG(SALARIO) AS SALARIO_MEDIO
FROM EMPLEADOS
GROUP BY DEP_NO
HAVING AVG(SALARIO) < 3000
ORDER BY SALARIO_MEDIO;

SELECT PRODUCTO_NO, SUM(UNIDADES)
FROM PEDIDOS
GROUP BY PRODUCTO_NO;

SELECT CLIENTE_NO, COUNT(*)
FROM PEDIDOS
GROUP BY CLIENTE_NO 
HAVING COUNT(*) > 2
ORDER BY 2;

SELECT LOCALIDAD, COUNT(*) AS NUM_CLIENTES
FROM CLIENTES
GROUP BY LOCALIDAD
HAVING COUNT(*) > 1;

SELECT PRODUCTO_NO, SUM(UNIDADES) AS UNIDADES_VENDIDAS
FROM PEDIDOS
GROUP BY PRODUCTO_NO
ORDER BY UNIDADES_VENDIDAS DESC
LIMIT 4;