USE CURSO;

SELECT OFICIO, EMP_NO
FROM EMPLEADOS;

SELECT OFICIO, COUNT(*)
FROM EMPLEADOS
GROUP BY OFICIO
ORDER BY 2 DESC;

SELECT SUM((SALARIO+IFNULL(COMISION, 0))*14) AS MASA_SALARIAL
FROM EMPLEADOS;

SELECT DEP_NO, COUNT(*) AS 'Número_Empleados'
FROM EMPLEADOS
GROUP BY DEP_NO;

SELECT COUNT(DISTINCT OFICIO) AS 'NºOficios_Distintos'
FROM EMPLEADOS
WHERE DEP_NO = 30;

SELECT PRODUCTO_NO, 
MIN(FECHA_PEDIDO) AS pedido_mas_antiguo,
MAX(FECHA_PEDIDO) AS pedido_mas_reciente
FROM PEDIDOS
GROUP BY PRODUCTO_NO;

SELECT SUM(PRECIO_ACTUAL * STOCK_DISPONIBLE) AS TOTAL
FROM PRODUCTOS;

SELECT DEP_NO, COUNT(*) AS CONTEO, AVG(SALARIO) AS SALARIO_MEDIO
FROM EMPLEADOS
WHERE OFICIO = 'VENDEDOR'
GROUP BY DEP_NO
HAVING AVG(SALARIO) > 1200;

SELECT DEP_NO, AVG(SALARIO) AS SALARIO_MEDIO
FROM EMPLEADOS
GROUP BY DEP_NO
ORDER BY SALARIO_MEDIO DESC
LIMIT 1;

SELECT PRODUCTO_NO, CLIENTE_NO, SUM(unidades)
FROM PEDIDOS
GROUP BY PRODUCTO_NO, CLIENTE_NO;

SELECT PRODUCTO_NO, COUNT(*) AS num_pedido
FROM PEDIDOS
WHERE FECHA_PEDIDO > '2000-01-01'
GROUP BY PRODUCTO_NO
HAVING num_pedido > 1;

SELECT CLIENTE_NO, COUNT(*) AS NUM_PEDIDOS
FROM PEDIDOS
GROUP BY CLIENTE_NO
ORDER BY NUM_PEDIDOS DESC
LIMIT 2;